bayesian-vh-rescorer : posterior_flow.cpp zutil.cxx util.cxx fasta-io.cxx posterior_flow.h zutil.h util.h fasta-io.h
	g++ posterior_flow.cpp util.cxx zutil.cxx fasta-io.cxx -O2 -g -o bayesian-vh-rescorer 
